version: '3.8'

services:
  # 1. Database PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: jfintech-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=jfintech
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jfintech-net

  # 2. PgAdmin (Giao diện quản lý DB - Giống phpMyAdmin nhưng cho Postgres)
  pgadmin:
    image: dpage/pgadmin4
    container_name: jfintech-pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@jfintech.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - jfintech-net

volumes:
  postgres_data:

networks:
  jfintech-net:
    driver: bridge